### ISSUE TITLE
Similar goals in CeranPaul/SketchCurves

### ISSUE THREAD

**Issue by CeranPaul** [tonystone/geofeatures2#166]
Hello!  I am also working on a geometry tool library as referenced above.  You might find something useful there.   Paul

**Comment by tonystone** [comment]
Hi Paul, thanks for letting me know about your project, I’ll look it over.  In general what is the goal of your project?

We are currently working on the math functions within our geometries at the moment such as intersection, union, etc.

- Tony

**Comment by CeranPaul** [comment]
Two goals:  build a collection of geometry tools that will allow me to use an iPad and Pencil to create simple parts for 3D printing;  and have a repository where employers can see my programming skills.

The intersections my code can currently do are line & line and plane & plane.  Because the solids I’m interested in will usually have one or more bicubic surfaces, I’m months away from having that ability.

     Paul H.
